# Clans config

# Maximum time (in seconds) to confirm destructive commands (i.e. disband) after initializing them.
# Default: 30 seconds
confirmTime: 30

# Whether to integrate with Minecraft scoreboard teams.
# This will result in clan members being placed in scoreboard teams corresponding to their clans.
# Using this, you can color players as they join the game.
# Default: true

# NOTE: CHANGING THIS OPTION AFTER THE SERVER IS LAUNCHED MAY HAVE UNDESIRED AFFECTS!
scoreboardTeamsIntegration: True