name: Clans
main: net.williserver.clans.ClansPlugin
version: 1.0
api-version: 1.21

commands:
  clans:
    description: Base command for interfacing with clans plugin.
    usage: "Use /clans help for usage information."